directive @model(tsType: String!, from: String!) on OBJECT

type Query {
  homeChannel: Channel
}

type Channel @model(tsType: "ChannelModel", from: "./models.ts") {
  id: ID!
  description: String
  team: Team
}

type Team {
  id: ID!
  title: String
}
